name: Build SubSpell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: SubSpell-Windows
            artifact_path: dist/SubSpell.exe
          - os: macos-latest
            artifact_name: SubSpell-macOS
            artifact_path: dist/SubSpell.app
          - os: ubuntu-latest
            artifact_name: SubSpell-Linux
            artifact_path: dist/SubSpell

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow google-generativeai pysubs2
    
    - name: Build executable
      run: python build_gui.py
    
    - name: Sign Windows executable
      if: matrix.os == 'windows-latest'
      run: |
        # Download certificate from secrets
        echo "${{ secrets.WINDOWS_CERT_BASE64 }}" | base64 -d > cert.pfx
        
        # Set environment variables for signing
        echo "SIGN_CERTIFICATE=cert.pfx" >> $GITHUB_ENV
        echo "SIGN_PASSWORD=${{ secrets.WINDOWS_CERT_PASSWORD }}" >> $GITHUB_ENV
        
        # Sign the executable
        signtool sign /f cert.pfx /p ${{ secrets.WINDOWS_CERT_PASSWORD }} /t http://timestamp.digicert.com /d "Subtitle Spelling and Grammar Correction Tool" /v dist/SubSpell.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }} 