name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        pip install -e .
    
    - name: Generate icon
      run: python generate_icon.py
    
    - name: Build executable
      run: python build_gui.py
    
    - name: Sign Windows executable
      if: matrix.os == 'windows-latest'
      run: |
        # Download certificate from secrets
        echo "${{ secrets.WINDOWS_CERT_BASE64 }}" | base64 -d > cert.pfx
        
        # Set environment variables for signing
        echo "WINDOWS_CERT_PATH=cert.pfx" >> $GITHUB_ENV
        echo "WINDOWS_CERT_PASSWORD=${{ secrets.WINDOWS_CERT_PASSWORD }}" >> $GITHUB_ENV
        
        # Sign the executable
        signtool sign /f cert.pfx /p ${{ secrets.WINDOWS_CERT_PASSWORD }} /t http://timestamp.digicert.com /d "Subtitle Spelling and Grammar Correction Tool" /v dist/SubSpell.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SubSpell-${{ matrix.os }}
        path: |
          dist/SubSpell.exe
          dist/SubSpell.app
          dist/SubSpell
        if-no-files-found: error 