name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        pip install -e .
    
    - name: Generate icon
      run: python generate_icon.py
    
    - name: Build executable
      run: python build_gui.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SubSpell-${{ matrix.os }}
        path: |
          dist/SubSpell.exe
          dist/SubSpell.app
          dist/SubSpell
        if-no-files-found: error 