name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    needs: build-executables
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: SubSpell-windows-latest
        path: dist/windows
    - uses: actions/download-artifact@v3
      with:
        name: SubSpell-macos-latest
        path: dist/macos
    - uses: actions/download-artifact@v3
      with:
        name: SubSpell-ubuntu-latest
        path: dist/linux
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          dist/windows/SubSpell.exe
          dist/macos/SubSpell.app
          dist/linux/SubSpell

  build-executables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        pip install -e .
    
    - name: Generate icon
      run: python generate_icon.py
    
    - name: Build executable
      run: python build_gui.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SubSpell-${{ matrix.os }}
        path: |
          dist/SubSpell.exe
          dist/SubSpell.app
          dist/SubSpell
        if-no-files-found: error 